// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhuv-JcHGx5VsuAXLYlT9yo3cu4Lzl9_k',
    appId: '1:666249880557:web:1527c9ae8b26d4075b7de4',
    messagingSenderId: '666249880557',
    projectId: 'dev-naporoge',
    authDomain: 'dev-naporoge.firebaseapp.com',
    storageBucket: 'dev-naporoge.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmju8--0KfZ8BpWQUhGYqHu1MyOtlMDP8',
    appId: '1:666249880557:android:100b519a3fdf00a25b7de4',
    messagingSenderId: '666249880557',
    projectId: 'dev-naporoge',
    storageBucket: 'dev-naporoge.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIM5PVMDrvANBQCEgYi1qa9D_ACSTEkqc',
    appId: '1:666249880557:ios:effaae88a8a2f9315b7de4',
    messagingSenderId: '666249880557',
    projectId: 'dev-naporoge',
    storageBucket: 'dev-naporoge.appspot.com',
    iosBundleId: 'ru.naporoge.umadmin2',
  );
}
